### ISSUE TITLE
Ainda consigo achar os vídeos para estudo?

### ISSUE THREAD

**Issue by wjard** [danielschmitz/tindev#4]
Olá,
Você teria os videos? Pois os mesmos já foram removidos do Youtube

**Comment by danielschmitz** [comment]
https://mega.nz/#!Kl0HVAQT!AhC_GrrILjrssrVqynOad2eIZaiAJMX0oJcY7TIu8YY

**Comment by wjard** [comment]
show.
valeu demais

**Comment by lauraleamari** [comment]
Bom dia, 
Você ainda possue os vídeos?
